name: MLOps CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-train-model:
    name: Run Tests for Training
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: |
        pytest -s tests/test_train.py
      env:
        PYTHONPATH: .

    - name: Run Quantization
      run: python src/quantize.py

  docker-build-and-predict:
    name: Build & Run Docker with predict.py
    runs-on: ubuntu-latest
    needs: test-train-model

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build -t mlops-final .

    - name: Run Container to Predict
      run: docker run --rm mlops-final